// Tests for web/js/decoder.js.
//
// Two layers: parity against every case in web/test/vectors.json (generated by
// tools/export_vectors.py from the Python reference; text, ditMs and offsetMs
// must match to 1e-6), and the decoder's own edge cases mirrored from
// tests/test_decoder.py with hand-built run sequences.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { Run } from "../js/runs.js";
import { encode } from "../js/table.js";
import {
  DEFAULT_DIT_MS,
  DEFAULT_MAX_MARK_MS,
  MorseDecoder,
  nearestRankPercentile,
} from "../js/decoder.js";

const vectors = JSON.parse(readFileSync(new URL("./vectors.json", import.meta.url), "utf8"));

const TOL = 1e-6;

// --------------------------------------------------------------------- helpers

/** `assert` that two numbers agree to `tol` (absolute). */
function assertClose(actual, expected, tol = TOL, message = "") {
  assert.ok(
    Math.abs(actual - expected) <= tol,
    `${message} expected ${expected} +- ${tol}, got ${actual}`,
  );
}

/** Python's `round()`: half to even. */
function pyRound(x) {
  const f = Math.floor(x);
  const diff = x - f;
  if (diff > 0.5) return f + 1;
  if (diff < 0.5) return f;
  return f % 2 === 0 ? f : f + 1;
}

/** Small seeded PRNG (mulberry32) for the jitter tests; uniform in [0, 1). */
function makeRng(seed) {
  let a = (seed >>> 0) || 0x9e3779b9;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** `"SOS X"` -> `"... --- ... / -..-"` using the shared table. */
const textToCode = (text) => encode(text);

/**
 * Turn a dot/dash string (`"... --- / -..-"`) into keyed `[on, ms]` pairs.
 * Standard timing: dit 1, dah 3, intra-letter gap 1, letter gap 3, word gap 7.
 */
function codeToPattern(code, ditMs) {
  const pattern = [];
  code.split(" / ").forEach((word, wi) => {
    if (wi) pattern.push([false, 7 * ditMs]);
    word.split(" ").forEach((letter, li) => {
      if (li) pattern.push([false, 3 * ditMs]);
      [...letter].forEach((symbol, si) => {
        if (si) pattern.push([false, ditMs]);
        pattern.push([true, symbol === "." ? ditMs : 3 * ditMs]);
      });
    });
  });
  return pattern;
}

/**
 * Distort a keyed pattern and quantise it to detector blocks.
 * `jitter` scales each duration by a uniform factor in `1 +- jitter`;
 * `offsetMs` lengthens marks and shortens gaps (reverb + detector release).
 */
function patternToRuns(pattern, { jitter = 0, offsetMs = 0, seed = 0, blockMs = 10 } = {}) {
  const rng = makeRng(seed);
  return pattern.map(([on, ms0]) => {
    let ms = ms0;
    if (jitter) ms *= 1 + (-jitter + rng() * 2 * jitter);
    ms += on ? offsetMs : -offsetMs;
    return new Run(on, Math.max(1, pyRound(ms / blockMs)), blockMs);
  });
}

/** Runs for `text` keyed at `wpm`; `opts` go to `patternToRuns`. */
function makeRuns(text, wpm, opts = {}) {
  return patternToRuns(codeToPattern(textToCode(text), 1200 / wpm), opts);
}

/** Feed every run, optionally flush with a long idle, return `{emitted, dec}`. */
function decodeRuns(runs, { flush = true, ...decoderOpts } = {}) {
  const dec = new MorseDecoder(decoderOpts);
  let emitted = "";
  for (const run of runs) emitted += dec.feed(run);
  if (flush) emitted += dec.idle(1_000_000);
  return { emitted, dec };
}

function speedChangeRuns(firstWpm, secondWpm, secondText) {
  const slowDit = 1200 / Math.min(firstWpm, secondWpm);
  return [
    ...makeRuns("PARIS PARIS", firstWpm),
    new Run(false, pyRound((7 * slowDit) / 10)),
    ...makeRuns(secondText, secondWpm),
  ];
}

const R = (on, blocks) => new Run(on, blocks);

// Loopback fixture after debounce: marks 110/270 ms, gaps 50/210 ms for keyed
// 80/240 ms (docs/PLAN.md section 4), i.e. d = 30 ms.
const PLAN_SECTION_4_RUNS = [
  R(true, 11), R(false, 5), R(true, 11), R(false, 5), R(true, 11),
  R(false, 21),
  R(true, 27), R(false, 5), R(true, 27), R(false, 5), R(true, 27),
  R(false, 21),
  R(true, 11), R(false, 5), R(true, 11), R(false, 5), R(true, 11),
];

const LETTER_GAP_15WPM = R(false, 24); // 3 dits at 15 WPM = 240 ms
const WORD_GAP_15WPM = R(false, 56); // 7 dits at 15 WPM = 560 ms
const SIX_SECOND_MARK = R(true, 600);

const runPairs = (runs) => runs.map((r) => [r.on, r.ms]);

// ------------------------------------------------------------- helper sanity

test("makeRuns SOS at 15 WPM matches standard timing", () => {
  assert.deepEqual(runPairs(makeRuns("SOS", 15)), [
    [true, 80], [false, 80], [true, 80], [false, 80], [true, 80],
    [false, 240],
    [true, 240], [false, 80], [true, 240], [false, 80], [true, 240],
    [false, 240],
    [true, 80], [false, 80], [true, 80], [false, 80], [true, 80],
  ]);
});

test("makeRuns word gap and reverb offset", () => {
  assert.deepEqual(runPairs(makeRuns("E E", 10, { offsetMs: 30 })), [[true, 150], [false, 810], [true, 150]]);
});

test("pyRound rounds half to even like Python", () => {
  assert.equal(pyRound(0.5), 0);
  assert.equal(pyRound(1.5), 2);
  assert.equal(pyRound(2.5), 2);
  assert.equal(pyRound(2.51), 3);
  assert.equal(pyRound(2.49), 2);
});

test("percentile is nearest-rank and never interpolates", () => {
  const range = (a, b) => Array.from({ length: b - a }, (_, i) => a + i);
  assert.equal(nearestRankPercentile([120, 240, 360], 10), 120); // interpolated: 144
  assert.equal(nearestRankPercentile([120, 360], 10), 120); // interpolated: 144
  assert.equal(nearestRankPercentile(range(1, 11), 10), 1); // n <= 10: the minimum
  assert.equal(nearestRankPercentile(range(1, 12), 10), 2); // ceil(1.1) = 2
  assert.equal(nearestRankPercentile(range(1, 21), 10), 2); // ceil(2.0) = 2
  assert.equal(nearestRankPercentile(range(1, 22), 10), 3); // ceil(2.1) = 3
  assert.equal(nearestRankPercentile(range(1, 31), 10), 3); // the default window
  assert.equal(nearestRankPercentile([5], 10), 5);
  assert.equal(nearestRankPercentile([7, 1], 10), 1);
  assert.equal(nearestRankPercentile([3.5, 1.5, 2.5], 50), 2.5); // ceil(1.5) = 2
  assert.equal(nearestRankPercentile([3.5, 1.5, 2.5], 100), 3.5);
  assert.equal(nearestRankPercentile([3.5, 1.5, 2.5], 0), 1.5); // rank 0 clamps to the minimum
  assert.throws(() => nearestRankPercentile([], 10), RangeError);
});

test("percentile result is always an observed value and sorts numerically", () => {
  const rng = makeRng(7);
  for (let n = 1; n < 40; n++) {
    const values = Array.from({ length: n }, () => 50 + rng() * 350);
    for (const q of [0, 10, 50, 90, 100]) assert.ok(values.includes(nearestRankPercentile(values, q)));
  }
  // a lexicographic sort would put 1000 before 200
  assert.equal(nearestRankPercentile([1000, 200, 30], 10), 30);
});

// ------------------------------------------------------- parity with Python

test("vectors.json has the expected shape", () => {
  assert.equal(vectors.schema_version, 1);
  assert.equal(vectors.params.decoder_constants.percentile, 10);
  assert.equal(vectors.params.decoder_constants.default_dit_ms, DEFAULT_DIT_MS);
  assert.equal(vectors.params.decoder.max_mark_ms, DEFAULT_MAX_MARK_MS);
  assert.ok(vectors.cases.length >= 7);
  const names = vectors.cases.map((c) => c.name);
  for (const expected of [
    "sos-15wpm-clean", "hello-world-8wpm", "jitter-20pct-12wpm-seed1", "reverb-30ms-15wpm",
    "speed-change-12-to-6wpm", "unknown-symbol", "idle-flush",
  ]) {
    assert.ok(names.includes(expected), expected);
  }
});

for (const c of vectors.cases) {
  test(`parity: ${c.name}`, () => {
    const dec = new MorseDecoder({ wpm: c.decoder.wpm, adaptive: c.decoder.adaptive, window: c.decoder.window });
    const runs = c.runs.map((pair) => Run.fromPair(pair, vectors.params.block_ms));
    let before = "";
    for (const run of runs) before += dec.feed(run);
    assert.equal(before, c.text_before_idle, "text emitted by feed()");
    for (const [offMs, expected] of c.idle_probes) {
      assert.equal(dec.idle(offMs), expected, `idle(${offMs})`);
    }
    assert.equal(dec.idle(Infinity), c.idle_text, "idle(Infinity)");
    assert.equal(dec.text, c.text);
    assertClose(dec.ditMs, c.dit_ms, TOL, "ditMs");
    assertClose(dec.offsetMs, c.offset_ms, TOL, "offsetMs");
    assert.equal(dec.letterCount, c.letter_count);
    assert.equal(dec.unknownCount, c.unknown_count);
    assert.equal(dec.buffer, "");
  });
}

test("parity: the test helpers reproduce the vector run lists (no jitter)", () => {
  const byName = Object.fromEntries(vectors.cases.map((c) => [c.name, c]));
  const pairs = (runs) => runs.map((r) => [r.on, r.blocks]);
  assert.deepEqual(pairs(makeRuns("SOS", 15)), byName["sos-15wpm-clean"].runs);
  assert.deepEqual(pairs(makeRuns("HELLO WORLD", 8)), byName["hello-world-8wpm"].runs);
  assert.deepEqual(pairs(makeRuns("SOS", 15, { offsetMs: 30 })), byName["reverb-30ms-15wpm"].runs);
  assert.deepEqual(
    pairs(speedChangeRuns(12, 6, "PARIS PARIS PARIS PARIS")),
    byName["speed-change-12-to-6wpm"].runs,
  );
  assert.deepEqual(
    pairs(patternToRuns(codeToPattern("...... / ...", 1200 / 15))),
    byName["unknown-symbol"].runs,
  );
});

// ------------------------------------------------------------ clean decoding

test("SOS clean at 15 WPM", () => {
  const { emitted, dec } = decodeRuns(makeRuns("SOS", 15));
  assert.equal(emitted, "SOS ");
  assert.equal(dec.text, "SOS ");
  assertClose(dec.ditMs, 80);
  assertClose(dec.offsetMs, 0);
  assertClose(dec.wpm, 15);
  assert.equal(dec.letterCount, 3);
  assert.equal(dec.unknownCount, 0);
  assert.equal(dec.buffer, "");
});

test("HELLO WORLD at 8 WPM with word spacing", () => {
  const { emitted, dec } = decodeRuns(makeRuns("HELLO WORLD", 8));
  assert.equal(emitted, "HELLO WORLD ");
  assertClose(dec.ditMs, 150);
  assert.equal(dec.letterCount, 10);
});

test("feed returns only new text and text accumulates", () => {
  const dec = new MorseDecoder();
  const pieces = makeRuns("SOS SOS", 15).map((run) => dec.feed(run));
  pieces.push(dec.idle(10_000));
  const count = pieces.reduce((n, p) => n + (p.match(/S/g) || []).length, 0);
  assert.equal(count, 4, "each letter is returned exactly once");
  assert.equal(pieces.join(""), dec.text);
  assert.equal(dec.text, "SOS SOS ");
  assert.deepEqual(pieces.slice(0, 5), ["", "", "", "", ""]);
  for (const p of pieces) assert.ok(["", "S", "O", "S "].includes(p), JSON.stringify(p));
});

test("20 % jitter at 12 WPM still decodes (20 seeds, three texts)", () => {
  for (const text of ["HELLO WORLD", "PARIS PARIS PARIS", "SOS SOS SOS"]) {
    for (let seed = 0; seed < 20; seed++) {
      const { emitted, dec } = decodeRuns(makeRuns(text, 12, { jitter: 0.2, seed }));
      assert.equal(emitted.trim(), text, `${text} seed ${seed}`);
      // M is the 10th percentile of jittered dits, so it sits below the true dit
      assert.ok(dec.ditMs >= 0.75 * 100 && dec.ditMs <= 1.05 * 100, `${text} seed ${seed}: ditMs ${dec.ditMs}`);
    }
  }
});

test("digits and punctuation decode", () => {
  // 'C' opens with a dah. The first runs are held back until both mark
  // classes have been seen, so no WPM seed is needed any more (it still works).
  let r = decodeRuns(makeRuns("CQ DE W1AW 73 K.", 15, { jitter: 0.1, seed: 3 }), { wpm: 15 });
  assert.equal(r.emitted.trim(), "CQ DE W1AW 73 K.");
  r = decodeRuns(makeRuns("CQ DE W1AW 73 K.", 15, { jitter: 0.1, seed: 3 }));
  assert.equal(r.emitted.trim(), "CQ DE W1AW 73 K.");
  r = decodeRuns(makeRuns("ITS 73 DE W1AW K.", 15, { jitter: 0.1, seed: 3 }));
  assert.equal(r.emitted.trim(), "ITS 73 DE W1AW K.");
});

// ----------------------------------------------------- hold-back and dah rule

test("messages opening with dah letters decode without a seed", () => {
  for (const text of ["OSO", "TEST", "MOM", "MORSE CODE", "OK", "0 TO 9", "TT EEE"]) {
    for (const wpm of [8, 15, 25]) {
      const { emitted, dec } = decodeRuns(makeRuns(text, wpm));
      assert.equal(emitted.trim(), text, `${text} @ ${wpm}`);
      assertClose(dec.ditMs / (1200 / wpm), 1, 0.06, `${text} @ ${wpm}: ditMs`);
    }
  }
});

test("slow keying down to 2 WPM", () => {
  for (const wpm of [2, 3, 4, 5, 6, 7]) {
    for (const text of ["SOS HELLO", "HELLO WORLD", "TEST 123"]) {
      const { emitted, dec } = decodeRuns(makeRuns(text, wpm));
      assert.equal(emitted.trim(), text, `${text} @ ${wpm}`);
      assertClose(dec.ditMs / (1200 / wpm), 1, 0.06, `${text} @ ${wpm}: ditMs`);
    }
  }
});

test("runs are held back until the estimate is trusted", () => {
  const dec = new MorseDecoder();
  const runs = makeRuns("SOS", 3); // 400 ms dits: the old seed read the first one as a dah
  assert.equal(dec.timingReady, false);
  let out = "";
  for (const r of runs.slice(0, 3)) out += dec.feed(r); // dit, gap, dit: one class, not trusted
  assert.equal(out, "");
  assert.equal(dec.buffer, "");
  assert.equal(dec.timingReady, false);
  assert.equal(dec.pendingCount, 3);
  assert.equal(dec.provisional, "..");
  out = "";
  for (const r of runs.slice(3, 5)) out += dec.feed(r); // gap, third dit: trusted, replays
  assert.equal(dec.timingReady, true);
  assert.equal(dec.pendingCount, 0);
  assert.equal(out, "");
  assert.equal(dec.buffer, "...");
  assert.equal(dec.provisional, "");
  assert.equal(dec.feed(runs[5]), "S"); // letter gap closes S
  assert.equal(dec.feed(runs[6]), "");
  assert.equal(dec.buffer, "-");
  assertClose(dec.ditMs, 400);
});

test("three marks of one class are enough to trust", () => {
  const dec = new MorseDecoder();
  let out = "";
  for (const r of makeRuns("EI", 10)) out += dec.feed(r); // dits only
  assert.equal(dec.timingReady, true); // trusted at the 3rd mark
  out += dec.idle(1_000_000);
  assert.equal(out.trim(), "EI");
});

test("idle flushes held runs with the best estimate", () => {
  assert.equal(decodeRuns(makeRuns("E", 15)).emitted, "E ");
  assert.equal(decodeRuns(makeRuns("T", 8)).emitted, "T ");
  assert.equal(decodeRuns(makeRuns("S", 3)).emitted, "S ");
  const { emitted, dec } = decodeRuns(makeRuns("O", 15));
  assert.equal(emitted, "O "); // dah rule: marks are 3x the intra gaps
  assertClose(dec.ditMs, 80);
});

test("held runs wait for a slow letter gap before flushing", () => {
  const dec = new MorseDecoder();
  const [e1, gap, e2] = makeRuns("EE", 2);
  assert.equal(dec.feed(e1), "");
  assert.equal(dec.idle(1700), ""); // limit is max(7 x 150, 3.5 x 600) = 2100 ms
  assert.equal(dec.feed(gap), "");
  let out = dec.feed(e2);
  assert.equal(dec.timingReady, false);
  out += dec.idle(1_000_000);
  assert.equal(out, "EE ");
});

test("an over-long mark clears held runs too", () => {
  const dec = new MorseDecoder();
  for (const r of makeRuns("S", 3).slice(0, 3)) dec.feed(r); // dit, gap, dit: still held
  assert.equal(dec.pendingCount, 3);
  assert.equal(dec.feed(R(true, 600)), "");
  assert.equal(dec.pendingCount, 0);
  assert.equal(dec.buffer, "");
  assert.equal(dec.unknownCount, 0);
});

test("adoptTiming transfers speed and offset", () => {
  const { dec: source } = decodeRuns(makeRuns("PARIS PARIS", 15, { offsetMs: 30 }));
  const fresh = new MorseDecoder();
  assert.equal(fresh.timingReady, false);
  fresh.adoptTiming(source);
  assert.equal(fresh.timingReady, true);
  assertClose(fresh.ditMs, source.ditMs);
  assertClose(fresh.offsetMs, source.offsetMs);
  assert.equal(fresh.text, "");
  const manual = new MorseDecoder({ wpm: 10, adaptive: false });
  manual.adoptTiming(source);
  assertClose(manual.ditMs, 120);
  assertClose(manual.offsetMs, source.offsetMs);
  let out = "";
  for (const r of makeRuns("SOS", 15, { offsetMs: 30 })) out += fresh.feed(r);
  out += fresh.idle(1_000_000);
  assert.equal(out.trim(), "SOS");
});

test("reset clears held runs and trust", () => {
  const dec = new MorseDecoder();
  for (const r of makeRuns("SO", 15)) dec.feed(r);
  assert.equal(dec.timingReady, true);
  dec.reset();
  assert.equal(dec.timingReady, false);
  assert.equal(dec.pendingCount, 0);
  const dec2 = new MorseDecoder();
  for (const r of makeRuns("SO", 15)) dec2.feed(r);
  dec2.reset(true);
  assert.equal(dec2.timingReady, true);
  assertClose(dec2.ditMs, 80);
});

test("speed-change parity text is pinned to nearest rank", () => {
  const { emitted, dec } = decodeRuns(speedChangeRuns(12, 6, "PARIS PARIS PARIS PARIS"));
  assert.equal(emitted, "PARIS PARIS TTTT TT TTT TT TTT TTTT TT TTT TT TTE PARIS PARIS ");
  assert.equal(dec.ditMs, 200);
  assert.equal(dec.offsetMs, 0);
});

// ---------------------------------------------------------- reverb correction

test("reverb offset 30 ms at 15 WPM decodes and estimates the true dit", () => {
  const { emitted, dec } = decodeRuns(makeRuns("SOS", 15, { offsetMs: 30 }));
  assert.equal(emitted, "SOS ");
  assert.ok(Math.abs(dec.ditMs - 80) <= 8);
  assertClose(dec.offsetMs, 30);
  assert.ok(Math.abs(dec.wpm - 15) <= 1.5);
});

test("PLAN section 4 measured runs decode to SOS", () => {
  const { emitted, dec } = decodeRuns(PLAN_SECTION_4_RUNS);
  assert.equal(emitted, "SOS ");
  assertClose(dec.ditMs, 80);
  assertClose(dec.offsetMs, 30);
});

test("reverb offset with words and jitter", () => {
  const { emitted, dec } = decodeRuns(makeRuns("HELLO WORLD", 15, { offsetMs: 30, jitter: 0.1, seed: 1 }));
  assert.equal(emitted.trim(), "HELLO WORLD");
  assert.ok(dec.offsetMs >= 20 && dec.offsetMs <= 40, `offsetMs ${dec.offsetMs}`);
});

test("reverb correction is needed for the PLAN runs", () => {
  // With T taken as the shortest mark (110 ms) and no offset, the 210 ms
  // letter gaps fall below 2T = 220 ms and SOS collapses into one unknown symbol.
  const dec = new MorseDecoder({ wpm: 1200 / 110, adaptive: false });
  dec._updateTiming = () => {}; // freeze T = 110, d = 0
  assertClose(dec.ditMs, 110);
  assert.equal(dec.offsetMs, 0);
  const emitted = PLAN_SECTION_4_RUNS.map((r) => dec.feed(r)).join("") + dec.idle(10_000);
  assert.equal(emitted, "? ");
  assert.equal(dec.unknownCount, 1);
});

// ------------------------------------------------------------- speed changes

test("speed change 12 to 6 WPM: default window recovers", () => {
  const { emitted, dec } = decodeRuns(speedChangeRuns(12, 6, "PARIS PARIS PARIS PARIS"));
  assert.ok(emitted.startsWith("PARIS PARIS "), "text before the change is intact");
  assert.ok(emitted.endsWith(" PARIS PARIS "), "estimate re-locks on the new speed");
  assertClose(dec.ditMs, 200);
  assertClose(dec.wpm, 6);
});

test("speed change 12 to 6 WPM: small window recovers within two letters", () => {
  const { emitted, dec } = decodeRuns(speedChangeRuns(12, 6, "PARIS PARIS PARIS"), { window: 6 });
  assert.ok(emitted.startsWith("PARIS PARIS "));
  assert.ok(emitted.endsWith("RIS PARIS PARIS "), emitted);
  assertClose(dec.ditMs, 200);
});

test("speed change 6 to 12 WPM recovers within one letter", () => {
  const { emitted, dec } = decodeRuns(speedChangeRuns(6, 12, "PARIS PARIS PARIS"));
  assert.ok(emitted.startsWith("PARIS PARIS "));
  assert.ok(emitted.endsWith("ARIS PARIS PARIS "), emitted);
  assertClose(dec.ditMs, 100);
});

// ----------------------------------------------------------- unknown symbols

test("unknown symbol emits ? and counts", () => {
  const { emitted, dec } = decodeRuns(patternToRuns(codeToPattern("...... / ...", 1200 / 15)));
  assert.equal(emitted, "? S ");
  assert.equal(dec.unknownCount, 1);
  assert.equal(dec.letterCount, 2);
  assert.ok(dec.text.includes("?"));
});

test("unknown symbol flushed by idle counts too", () => {
  const runs = patternToRuns(codeToPattern("...... ", 1200 / 15).slice(0, -1));
  const dec = new MorseDecoder();
  for (const run of runs) dec.feed(run);
  assert.equal(dec.idle(10_000), "? ");
  assert.equal(dec.unknownCount, 1);
});

// ---------------------------------------------------------------- idle flush

test("idle flushes the last letter and adds a space exactly once", () => {
  const dec = new MorseDecoder();
  const emitted = makeRuns("SOS", 15).map((run) => dec.feed(run)).join("");
  assert.equal(emitted, "SO");
  assert.equal(dec.buffer, "...");
  assertClose(dec.ditMs, 80);
  // 7 * 80 = 560 ms: the flush needs offMs + offsetMs strictly greater
  assert.equal(dec.idle(560), "");
  assert.equal(dec.buffer, "...");
  assert.equal(dec.idle(570), "S ");
  assert.equal(dec.text, "SOS ");
  assert.equal(dec.buffer, "");
  assert.equal(dec.idle(600), "");
  assert.equal(dec.idle(5000), "");
  assert.equal(dec.text, "SOS ");
  // when the long OFF run is eventually finalised it adds no second space
  assert.equal(dec.feed(R(false, 500)), "");
  assert.equal(dec.text, "SOS ");
  assert.equal(dec.letterCount, 3);
});

test("idle threshold uses the offset correction", () => {
  const dec = new MorseDecoder();
  for (const run of makeRuns("SOS", 15, { offsetMs: 30 })) dec.feed(run);
  assertClose(dec.offsetMs, 30);
  assertClose(dec.ditMs, 80);
  // measured OFF is 30 ms short of the true gap: 530 + 30 = 560 is not > 560
  assert.equal(dec.idle(530), "");
  assert.equal(dec.idle(540), "S ");
});

test("idle with an empty buffer does nothing", () => {
  const dec = new MorseDecoder();
  assert.equal(dec.idle(100_000), "");
  assert.equal(dec.idle(Infinity), "");
  assert.equal(dec.text, "");
  for (const run of makeRuns("E", 15)) dec.feed(run);
  assert.equal(dec.idle(10_000), "E ");
  assert.equal(dec.idle(20_000), "");
  assert.equal(dec.text, "E ");
});

// ------------------------------------------------------------ wpm and timing

test("wpm property equals 1200 / ditMs", () => {
  let dec = new MorseDecoder();
  assert.equal(dec.ditMs, DEFAULT_DIT_MS);
  assert.equal(DEFAULT_DIT_MS, 150);
  assertClose(dec.wpm, 1200 / 150);
  dec = new MorseDecoder({ wpm: 10 });
  assertClose(dec.ditMs, 120);
  assertClose(dec.wpm, 10);
  ({ dec } = decodeRuns(makeRuns("PARIS", 20)));
  assertClose(dec.ditMs, 60);
  assertClose(dec.wpm, 20);
});

test("fallback timing until two marks and one gap", () => {
  const dec = new MorseDecoder();
  assert.deepEqual([dec.ditMs, dec.offsetMs], [150, 0]);
  dec.feed(R(true, 8)); // one mark
  assert.deepEqual([dec.ditMs, dec.offsetMs], [150, 0]);
  dec.feed(R(false, 5)); // one gap, still only one mark
  assert.deepEqual([dec.ditMs, dec.offsetMs], [150, 0]);
  dec.feed(R(true, 8)); // second mark: estimate M=80, G=50
  assertClose(dec.ditMs, 65);
  assertClose(dec.offsetMs, 15);

  const seeded = new MorseDecoder({ wpm: 8 });
  assertClose(seeded.ditMs, 150);
  seeded.feed(R(true, 30));
  assertClose(seeded.ditMs, 150);
});

test("negative offset falls back to T = M", () => {
  const dec = new MorseDecoder();
  dec.feed(R(true, 8));
  dec.feed(R(false, 24)); // gap longer than the marks
  dec.feed(R(true, 8));
  assertClose(dec.ditMs, 80);
  assert.equal(dec.offsetMs, 0);
});

test("adaptive=false with wpm keeps the dit fixed and adapts the offset", () => {
  const dec = new MorseDecoder({ wpm: 10, adaptive: false });
  assertClose(dec.ditMs, 120);
  let emitted = "";
  for (const run of makeRuns("PARIS", 12)) {
    // sent at 12 WPM, decoder pinned to 10
    emitted += dec.feed(run);
    assertClose(dec.ditMs, 120);
  }
  emitted += dec.idle(10_000);
  assert.equal(emitted, "PARIS ");
  assertClose(dec.wpm, 10);

  const reverb = new MorseDecoder({ wpm: 10, adaptive: false });
  emitted = "";
  for (const run of makeRuns("PARIS", 10, { offsetMs: 30 })) {
    emitted += reverb.feed(run);
    assertClose(reverb.ditMs, 120);
  }
  emitted += reverb.idle(10_000);
  assert.equal(emitted, "PARIS ");
  assertClose(reverb.offsetMs, 30, TOL, "only d adapts");
});

test("adaptive=false without wpm still adapts", () => {
  const { dec } = decodeRuns(makeRuns("PARIS", 15), { adaptive: false });
  assertClose(dec.ditMs, 80);
});

test("wpm seed is overridden when adaptive", () => {
  const { emitted, dec } = decodeRuns(makeRuns("PARIS", 15), { wpm: 10 });
  assert.equal(emitted, "PARIS ");
  assertClose(dec.ditMs, 80);
});

test("thresholds at exact boundaries", () => {
  const dec = new MorseDecoder({ wpm: 10, adaptive: false }); // T = 120 fixed, d stays 0 here
  assert.equal(dec.feed(R(true, 12)), ""); // 120 < 240: dit
  assert.equal(dec.feed(R(false, 12)), ""); // intra-letter
  assert.equal(dec.feed(R(true, 24)), ""); // exactly 2T: dah
  assert.equal(dec.buffer, ".-");
  assert.equal(dec.feed(R(false, 24)), "A"); // exactly 2T ends the letter
  assert.equal(dec.feed(R(true, 12)), "");
  assert.equal(dec.feed(R(false, 60)), "E "); // exactly 5T ends the word
  assert.equal(dec.offsetMs, 0);
});

test("window limits the timing history", () => {
  const dec = new MorseDecoder({ window: 4 });
  for (const run of makeRuns("SOS", 15)) dec.feed(run);
  assertClose(dec.ditMs, 80);
  // eight slow dits and seven slow gaps push the fast runs out of a 4-run window
  for (const run of makeRuns("HH", 6)) dec.feed(run);
  assertClose(dec.ditMs, 200);
  assert.equal(dec.offsetMs, 0);
});

// ------------------------------------------------------- gaps, spaces, reset

test("leading gap emits nothing and is ignored for timing", () => {
  const dec = new MorseDecoder();
  assert.equal(dec.feed(R(false, 3000)), "");
  assert.equal(dec.feed(R(false, 50)), "");
  assert.equal(dec.text, "");
  assert.deepEqual([dec.ditMs, dec.offsetMs], [150, 0]);
  const emitted = makeRuns("SOS", 15).map((r) => dec.feed(r)).join("") + dec.idle(10_000);
  assert.equal(emitted, "SOS ");
  assertClose(dec.ditMs, 80);
});

test("word gap adds exactly one space", () => {
  const { emitted } = decodeRuns(makeRuns("SOS SOS", 15));
  assert.equal(emitted, "SOS SOS ");
  const dec = new MorseDecoder({ wpm: 15 }); // seeded: no hold-back, the lone E is classified at once
  for (const run of makeRuns("E", 15)) dec.feed(run);
  assert.equal(dec.feed(R(false, 100)), "E ");
  assert.equal(dec.feed(R(false, 100)), ""); // a second long gap adds no space
  assert.equal(dec.text, "E ");
});

test("very long gaps do not disturb the dit estimate (gap cap at 20 M)", () => {
  const runs = [];
  for (const word of ["SOS", "SOS", "SOS"]) runs.push(...makeRuns(word, 15), R(false, 1000)); // 10 s of silence
  const { emitted, dec } = decodeRuns(runs);
  assert.equal(emitted, "SOS SOS SOS ");
  assertClose(dec.ditMs, 80);
  assert.equal(dec.offsetMs, 0);
});

test("reset clears text and optionally timing", () => {
  const { dec } = decodeRuns(makeRuns("SOS", 15, { offsetMs: 30 }));
  assert.equal(dec.text, "SOS ");
  dec.reset(true);
  assert.equal(dec.text, "");
  assert.equal(dec.buffer, "");
  assert.equal(dec.letterCount, 0);
  assert.equal(dec.unknownCount, 0);
  assertClose(dec.ditMs, 80);
  assertClose(dec.offsetMs, 30);
  dec.reset();
  assert.deepEqual([dec.ditMs, dec.offsetMs], [150, 0]);
  const emitted = makeRuns("E", 15).map((r) => dec.feed(r)).join("") + dec.idle(10_000);
  assert.equal(emitted, "E ");

  const seeded = new MorseDecoder({ wpm: 10 });
  seeded.feed(R(true, 8));
  seeded.feed(R(false, 8));
  seeded.feed(R(true, 8));
  assertClose(seeded.ditMs, 80);
  seeded.reset();
  assertClose(seeded.ditMs, 120);
});

test("constructor validation", () => {
  assert.throws(() => new MorseDecoder({ wpm: 0 }), RangeError);
  assert.throws(() => new MorseDecoder({ wpm: -5 }), RangeError);
  assert.throws(() => new MorseDecoder({ wpm: NaN }), RangeError);
  assert.throws(() => new MorseDecoder({ window: 1 }), RangeError);
  assert.doesNotThrow(() => new MorseDecoder({ wpm: undefined }));
  assert.doesNotThrow(() => new MorseDecoder());
});

// ---------------------------------------------------------------- long marks
// A mark of maxMarkMs (default 5000) or longer is not a symbol: ignored, buffer
// cleared, nothing emitted, unknownCount untouched.

test("long mark between letters is ignored and the next letter survives", () => {
  const runs = [
    ...makeRuns("SO", 15),
    LETTER_GAP_15WPM, SIX_SECOND_MARK, LETTER_GAP_15WPM,
    ...makeRuns("S", 15),
  ];
  const dec = new MorseDecoder();
  const pieces = runs.map((run) => dec.feed(run));
  pieces.push(dec.idle(10_000));
  assert.equal(pieces.join(""), "SOS ");
  assert.equal(dec.text, "SOS ");
  assert.ok(!dec.text.includes("?"));
  assert.equal(dec.unknownCount, 0);
  assert.equal(dec.letterCount, 3);
  assert.equal(pieces[runs.indexOf(SIX_SECOND_MARK)], "");
  // the 6 s mark left the timing estimate exactly where SOS at 15 WPM puts it
  assertClose(dec.ditMs, 80);
  assert.equal(dec.offsetMs, 0);
});

test("long mark clears the pending buffer without counting unknown", () => {
  const dec = new MorseDecoder();
  for (const run of patternToRuns(codeToPattern("......", 1200 / 15))) dec.feed(run);
  assert.equal(dec.buffer, "......");
  assert.equal(dec.feed(SIX_SECOND_MARK), "");
  assert.equal(dec.buffer, "");
  assert.equal(dec.text, "");
  assert.equal(dec.unknownCount, 0);
  assert.equal(dec.letterCount, 0);
  assert.equal(dec.feed(LETTER_GAP_15WPM), "");
  assert.equal(dec.idle(10_000), "");
  assert.equal(dec.text, "");
  const emitted = makeRuns("E", 15).map((r) => dec.feed(r)).join("") + dec.idle(10_000);
  assert.equal(emitted, "E ");
  assert.equal(dec.unknownCount, 0);
});

test("long mark is excluded from the timing window", () => {
  const dec = new MorseDecoder({ window: 2 });
  for (const run of [R(true, 8), R(false, 8), R(true, 24), R(false, 8)]) dec.feed(run);
  assertClose(dec.ditMs, 80);
  dec.feed(SIX_SECOND_MARK);
  assertClose(dec.ditMs, 80);
  assert.equal(dec.offsetMs, 0);
});

test("long mark after a word gap adds no second space", () => {
  const runs = [...makeRuns("SOS", 15), WORD_GAP_15WPM, SIX_SECOND_MARK, WORD_GAP_15WPM, ...makeRuns("SOS", 15)];
  const { emitted, dec } = decodeRuns(runs);
  assert.equal(emitted, "SOS SOS ");
  assert.equal(dec.unknownCount, 0);
  assert.equal(dec.letterCount, 6);
});

test("long mark while idle leaves nothing to flush", () => {
  const dec = new MorseDecoder();
  for (const run of makeRuns("S", 15)) dec.feed(run);
  assert.equal(dec.buffer, "..."); // trusted at the third dit
  assert.equal(dec.pendingCount, 0);
  dec.feed(SIX_SECOND_MARK);
  assert.equal(dec.buffer, "");
  assert.equal(dec.idle(Infinity), "");
  assert.equal(dec.text, "");
});

test("leading long mark emits nothing and the message decodes afterwards", () => {
  const dec = new MorseDecoder();
  assert.equal(dec.feed(SIX_SECOND_MARK), "");
  assert.equal(dec.feed(R(false, 100)), "");
  assert.equal(dec.text, "");
  assert.deepEqual([dec.ditMs, dec.offsetMs], [150, 0]);
  const emitted = makeRuns("SOS", 15).map((r) => dec.feed(r)).join("") + dec.idle(10_000);
  assert.equal(emitted, "SOS ");
  assertClose(dec.ditMs, 80);
});

test("beeper fixture marks up to 3700 ms are still symbols", () => {
  const runs = [
    R(true, 370), R(false, 37), R(true, 49), R(false, 25),
    R(true, 57), R(false, 30), R(true, 202),
  ];
  const dec = new MorseDecoder();
  assert.equal(dec.feed(runs[0]), "");
  assert.equal(dec.pendingCount, 1, "3.7 s is held back, not ignored");
  // 3.7 s is a dah; the others read as dits and a dah against T = 430 ms: "-..-".
  const emitted = runs.slice(1).map((r) => dec.feed(r)).join("") + dec.idle(Infinity);
  assert.equal(emitted, "X ");
  assert.equal(dec.letterCount, 1);
  assert.equal(dec.unknownCount, 0);
});

test("marks up to maxMarkMs decode and longer ones are ignored (boundary)", () => {
  assert.equal(DEFAULT_MAX_MARK_MS, 5000);
  const cases = [
    [37, "T"], // 3700 ms beeper
    [202, "T"], // 2020 ms beeper
    [499, "T"], // 4990 ms
    [500, ""], // exactly maxMarkMs is ignored
    [501, ""], // one block over
    [600, ""],
    [100_000, ""], // 1000 s
  ];
  for (const [blocks, expected] of cases) {
    const dec = new MorseDecoder({ wpm: 15, adaptive: false }); // T = 80 fixed, d = 0
    assert.equal(dec.maxMarkMs, 5000);
    assert.equal(dec.feed(R(true, blocks)), "", `${blocks} blocks`);
    assert.equal(dec.buffer, expected ? "-" : "", `${blocks} blocks`);
    assert.equal(dec.feed(LETTER_GAP_15WPM), expected, `${blocks} blocks`);
    assert.equal(dec.text, expected);
    assert.equal(dec.unknownCount, 0);
    assert.equal(dec.letterCount, expected.length);
  }
});

test("maxMarkMs is a constructor option and a settable property", () => {
  const dec = new MorseDecoder({ wpm: 15, adaptive: false, maxMarkMs: 1000 });
  assert.equal(dec.maxMarkMs, 1000);
  assert.equal(dec.feed(R(true, 99)), "");
  assert.equal(dec.buffer, "-"); // 990 ms: a dah
  assert.equal(dec.feed(R(true, 100)), "");
  assert.equal(dec.buffer, ""); // exactly 1000 ms: ignored, buffer cleared
  dec.maxMarkMs = 2000;
  assert.equal(dec.feed(R(true, 100)), "");
  assert.equal(dec.buffer, "-");
  assert.equal(dec.feed(R(true, 200)), "");
  assert.equal(dec.buffer, "");
  assert.equal(dec.unknownCount, 0);
  assert.equal(dec.letterCount, 0);

  const unlimited = new MorseDecoder({ wpm: 15, adaptive: false, maxMarkMs: Infinity });
  unlimited.feed(R(true, 6_000_000));
  assert.equal(unlimited.buffer, "-");
});

test("maxMarkMs survives reset", () => {
  const dec = new MorseDecoder({ maxMarkMs: 1234.5 });
  dec.reset();
  assert.equal(dec.maxMarkMs, 1234.5);
  dec.reset(true);
  assert.equal(dec.maxMarkMs, 1234.5);
});

test("maxMarkMs must be positive", () => {
  for (const bad of [0, -1, -5000, NaN]) {
    assert.throws(() => new MorseDecoder({ maxMarkMs: bad }), RangeError, String(bad));
  }
});

// -------------------------------------------------------------------- Run

test("Run mirrors the Python dataclass", () => {
  const run = new Run(true, 11);
  assert.equal(run.ms, 110);
  assert.equal(run.blockMs, 10);
  assert.equal(String(run), "ON 110 ms");
  assert.equal(String(new Run(false, 5)), "off 50 ms");
  assert.equal(new Run(true, 3, 20).ms, 60);
  assert.ok(Object.isFrozen(run));
  assert.throws(() => {
    run.blocks = 5;
  }, TypeError);
  assert.deepEqual(Run.fromPair([true, 7]), new Run(true, 7));
});


// ------------------------------------------------------------ glitch rejection

test("glitch marks after a message are ignored", () => {
  const noise = [
    R(false, 200), R(true, 3), R(false, 200), R(true, 4),
    R(false, 300), R(true, 2), R(false, 200), R(true, 5), R(false, 200),
  ];
  const { emitted, dec } = decodeRuns([...makeRuns("HELLO WORLD", 8), ...noise]);
  assert.equal(emitted, "HELLO WORLD ");
  assert.equal(dec.letterCount, 10);
  assert.equal(dec.unknownCount, 0);
  assertClose(dec.ditMs, 150);
  assert.equal(dec.offsetMs, 0);
});

test("a glitch inside a letter is ignored with its short gaps", () => {
  const dit = R(true, 15);
  const glitchedS = [dit, R(false, 15), dit, R(false, 5), R(true, 3), R(false, 7), dit];
  const { emitted, dec } = decodeRuns([...makeRuns("HELLO", 8), R(false, 105), ...glitchedS]);
  assert.equal(emitted, "HELLO S ");
  assert.ok(Math.abs(dec.ditMs - 150) <= 0.15 * 150, `ditMs ${dec.ditMs}`);
});

test("the glitch rule only applies once the estimate is trusted", () => {
  const dec = new MorseDecoder();
  assert.equal(dec.feed(R(true, 3)), "");
  assert.equal(dec.pendingCount, 1);
  assert.equal(decodeRuns(makeRuns("SOS", 40)).emitted.trim(), "SOS"); // 30 ms dits are legitimate at 40 WPM
});

test("provisional reading of held runs", () => {
  const dec = new MorseDecoder();
  dec.feed(makeRuns("O", 8)[0]);
  assert.equal(dec.provisional, "-"); // against the 150 ms seed a 450 ms mark is a dah
  dec.reset();
  dec.feed(makeRuns("E", 15)[0]);
  assert.equal(dec.provisional, ".");
  const dec2 = new MorseDecoder();
  for (const r of makeRuns("EE", 2)) dec2.feed(r);
  assert.equal(dec2.timingReady, false);
  assert.equal(dec2.provisional, ". ."); // letter gap shown as a space
});

test("a real speed-up of three times is accepted through the valve", () => {
  const runs = [...makeRuns("PARIS PARIS", 5), R(false, 168), ...makeRuns("PARIS PARIS PARIS", 15)];
  const { emitted, dec } = decodeRuns(runs);
  assert.ok(emitted.startsWith("PARIS PARIS "), emitted);
  assert.ok(emitted.endsWith("PARIS "), emitted);
  assert.ok(Math.abs(dec.ditMs - 80) <= 8, `ditMs ${dec.ditMs}`);
});
